# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import franka_control_pb2 as franka__control__pb2


class FrankaControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetJointTarget = channel.unary_unary(
                '/franka_control.FrankaControl/SetJointTarget',
                request_serializer=franka__control__pb2.JointTarget.SerializeToString,
                response_deserializer=franka__control__pb2.CommandResult.FromString,
                )
        self.GetRobotState = channel.unary_unary(
                '/franka_control.FrankaControl/GetRobotState',
                request_serializer=franka__control__pb2.Empty.SerializeToString,
                response_deserializer=franka__control__pb2.RobotState.FromString,
                )
        self.Stop = channel.unary_unary(
                '/franka_control.FrankaControl/Stop',
                request_serializer=franka__control__pb2.Empty.SerializeToString,
                response_deserializer=franka__control__pb2.CommandResult.FromString,
                )


class FrankaControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetJointTarget(self, request, context):
        """Set desired joint positions (7 doubles in radians)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotState(self, request, context):
        """Read current robot state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop the control loop gracefully
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrankaControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetJointTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointTarget,
                    request_deserializer=franka__control__pb2.JointTarget.FromString,
                    response_serializer=franka__control__pb2.CommandResult.SerializeToString,
            ),
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=franka__control__pb2.Empty.FromString,
                    response_serializer=franka__control__pb2.RobotState.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=franka__control__pb2.Empty.FromString,
                    response_serializer=franka__control__pb2.CommandResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'franka_control.FrankaControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FrankaControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetJointTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/franka_control.FrankaControl/SetJointTarget',
            franka__control__pb2.JointTarget.SerializeToString,
            franka__control__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/franka_control.FrankaControl/GetRobotState',
            franka__control__pb2.Empty.SerializeToString,
            franka__control__pb2.RobotState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/franka_control.FrankaControl/Stop',
            franka__control__pb2.Empty.SerializeToString,
            franka__control__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
