# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import franka_control_pb2 as franka__control__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in franka_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrankaControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetJointTarget = channel.unary_unary(
                '/franka_control.FrankaControl/SetJointTarget',
                request_serializer=franka__control__pb2.JointTarget.SerializeToString,
                response_deserializer=franka__control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.SetEETarget = channel.unary_unary(
                '/franka_control.FrankaControl/SetEETarget',
                request_serializer=franka__control__pb2.EETarget.SerializeToString,
                response_deserializer=franka__control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.SetGripperTarget = channel.unary_unary(
                '/franka_control.FrankaControl/SetGripperTarget',
                request_serializer=franka__control__pb2.GripperTarget.SerializeToString,
                response_deserializer=franka__control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.GetRobotState = channel.unary_unary(
                '/franka_control.FrankaControl/GetRobotState',
                request_serializer=franka__control__pb2.Empty.SerializeToString,
                response_deserializer=franka__control__pb2.RobotState.FromString,
                _registered_method=True)
        self.ResetToJoints = channel.unary_unary(
                '/franka_control.FrankaControl/ResetToJoints',
                request_serializer=franka__control__pb2.JointResetTarget.SerializeToString,
                response_deserializer=franka__control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/franka_control.FrankaControl/Stop',
                request_serializer=franka__control__pb2.Empty.SerializeToString,
                response_deserializer=franka__control__pb2.CommandResult.FromString,
                _registered_method=True)


class FrankaControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetJointTarget(self, request, context):
        """Set desired joint positions (7 doubles in radians)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEETarget(self, request, context):
        """Set desired end-effector pose (4x4 col-major, 16 doubles)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGripperTarget(self, request, context):
        """Set desired gripper opening width
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotState(self, request, context):
        """Read current robot + gripper state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetToJoints(self, request, context):
        """Move robot to a joint configuration (blocks until complete)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop the control loop gracefully
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrankaControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetJointTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointTarget,
                    request_deserializer=franka__control__pb2.JointTarget.FromString,
                    response_serializer=franka__control__pb2.CommandResult.SerializeToString,
            ),
            'SetEETarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEETarget,
                    request_deserializer=franka__control__pb2.EETarget.FromString,
                    response_serializer=franka__control__pb2.CommandResult.SerializeToString,
            ),
            'SetGripperTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGripperTarget,
                    request_deserializer=franka__control__pb2.GripperTarget.FromString,
                    response_serializer=franka__control__pb2.CommandResult.SerializeToString,
            ),
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=franka__control__pb2.Empty.FromString,
                    response_serializer=franka__control__pb2.RobotState.SerializeToString,
            ),
            'ResetToJoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetToJoints,
                    request_deserializer=franka__control__pb2.JointResetTarget.FromString,
                    response_serializer=franka__control__pb2.CommandResult.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=franka__control__pb2.Empty.FromString,
                    response_serializer=franka__control__pb2.CommandResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'franka_control.FrankaControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('franka_control.FrankaControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrankaControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetJointTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka_control.FrankaControl/SetJointTarget',
            franka__control__pb2.JointTarget.SerializeToString,
            franka__control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEETarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka_control.FrankaControl/SetEETarget',
            franka__control__pb2.EETarget.SerializeToString,
            franka__control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGripperTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka_control.FrankaControl/SetGripperTarget',
            franka__control__pb2.GripperTarget.SerializeToString,
            franka__control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka_control.FrankaControl/GetRobotState',
            franka__control__pb2.Empty.SerializeToString,
            franka__control__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetToJoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka_control.FrankaControl/ResetToJoints',
            franka__control__pb2.JointResetTarget.SerializeToString,
            franka__control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/franka_control.FrankaControl/Stop',
            franka__control__pb2.Empty.SerializeToString,
            franka__control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
